In [24]:
#import the required libraries
import numpy as np
import pandas as pd
import urllib

In [35]:
dataset = pd.read_csv('data/AviationData.csv', delimiter=',')
dataset.head()

,Event Id,Investigation Type,Accident Number,Event Date,Location,Country,Latitude,Longitude,Airport Code,Airport Name,...,Air Carrier,Total Fatal Injuries,Total Serious Injuries,Total Minor Injuries,Total Uninjured,Weather Condition,Broad Phase of Flight,Report Status,Publication Date,
0,20170601X43457,Accident,GAA17CA313,05/31/2017,Clovis~ NM,United States,,,CVN,,...,,,,,1,,,Preliminary,06/01/2017,
1,20170531X12547,Accident,GAA17CA312,05/30/2017,El Cajon~ CA,United States,32.826111,-116.972500,SEE,GILLESPIE FIELD,...,,,,,1,VMC,,Preliminary,06/01/2017,
2,20170531X31309,Accident,GAA17CA309,05/30/2017,Peyette~ ID,United States,44.094444,-116.903611,S75,PAYETTE MUNI,...,,,,,1,,,Preliminary,05/31/2017,
3,20170530X03313,Accident,GAA17CA308,05/27/2017,Lakeside~ TX,United States,32.814167,-97.553333,,N/A,...,,,,,2,VMC,,Preliminary,05/30/2017,
4,20170526X85142,Accident,GAA17CA305,05/26/2017,Develan~ CA,United States,,,,N/A,...,,,1,,,,,Preliminary,05/31/2017,

In [36]:
dataset.describe()

,Event Id,Investigation Type,Accident Number,Event Date,Location,Country,Latitude,Longitude,Airport Code,Airport Name,...,Air Carrier,Total Fatal Injuries,Total Serious Injuries,Total Minor Injuries,Total Uninjured,Weather Condition,Broad Phase of Flight,Report Status,Publication Date,
count,79954,79954,79954,79954,79954,79954,79954,79954,79954,79954,...,79954,79954,79954,79954,79954,79954,79954,79954,79954,79954
unique,78792,2,79954,12795,25434,178,18020,19323,9702,22917,...,2894,123,41,63,366,4,13,4,3630,1
top,20100204X45658,Accident,ERA09CA006,05/16/1982,ANCHORAGE~ AK,United States,,,,,...,,0,0,0,1,VMC,LANDING,Probable Cause,,
freq,3,76733,1,25,372,75282,53624,53633,34741,30113,...,76004,40091,42659,40063,22783,70996,19367,74426,13582,79954

In [37]:
dataset.tail()

,Event Id,Investigation Type,Accident Number,Event Date,Location,Country,Latitude,Longitude,Airport Code,Airport Name,...,Air Carrier,Total Fatal Injuries,Total Serious Injuries,Total Minor Injuries,Total Uninjured,Weather Condition,Broad Phase of Flight,Report Status,Publication Date,
79949,20041105X01764,Accident,CHI79FA064,08/02/1979,Canton~ OH,United States,,,,,...,,1,2,,,VMC,APPROACH,Probable Cause,04/16/1980,
79950,20001218X45448,Accident,LAX96LA321,06/19/1977,EUREKA~ CA,United States,,,,,...,,2,0,0,0,IMC,CRUISE,Probable Cause,09/12/2000,
79951,20061025X01555,Accident,NYC07LA005,08/30/1974,Saltville~ VA,United States,36.922223,-81.878056,,,...,,3,,,,IMC,CRUISE,Probable Cause,02/26/2007,
79952,20001218X45447,Accident,LAX94LA336,07/19/1962,BRIDGEPORT~ CA,United States,,,,,...,,4,0,0,0,UNK,UNKNOWN,Probable Cause,09/19/1996,
79953,20001218X45444,Accident,SEA87LA080,10/24/1948,MOOSE CREEK~ ID,United States,,,,,...,,2,0,0,0,UNK,CRUISE,Probable Cause,,